version: 2.1

orbs:
  node: circleci/node@1.1.4

jobs:
  build:
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-yarn
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run: npm run lint
      - run: npm run test
